### ISSUE TITLE
Node.js Training and Cert Sale: Linkedin and FB

### ISSUE THREAD

**Issue by RRomoff** [nodejs/social-team#3]
Hey y'all-
Our Training and Certification Sale is underway. We'd like to share the offer via Node.js Facebook and LinkedIn. The sale ends April 9 so we'd like these to go live no later than Monday, if possible. Thanks!

Facebook/ LinkedIn
Through April 9, Node.js Certifications and Trainings offered through the OpenJS Foundation and Linux Foundation are on sale. Save 75% on training and certification bundles. Also, there’s a new Preview of the Testing Environment available to help cert test takers best prepare. Learn more here: https://openjsf.org/certification/ 

Other Social Variations
If you've been waiting to get trained or certified in Node.js, all training courses and certifications offered by OpenJS Foundation are discounted up to 75% off thru April 9! Also, there’s a new Testing Environment preview available to help cert test takers best prepare. Check it out here: https://openjsf.org/certification/

Have you been waiting to get trained or certified in Node.js? Well now is the time! The OpenJS Foundation, in partnership with The Linux Foundation, is discounting trainings and certifications now through April 9! Save up to 75%. Also, learn more about the new Testing Environment preview, where test takers can preview what the certification exam experience is like before actually sitting for the exam. https://openjsf.org/certification/

**Comment by bnb** [comment]
Reframing the Facebook/LinkedIn one since it's structured as statements rather than a conversational voice, without a consistent thread that connects the ideas. Also dropping "Linux Foundation" since for the Node.js certification it's unnecessary additional context:

> Through April 9th, the OpenJS Foundation's has a 75% sale running on their Node.js Certifications and Trainings, alongside a new testing environment built for the Node.js Certifications: 
>
> https://openjsf.org/certification/

**Comment by RRomoff** [comment]
Edit for sale clarification-
Through April 9th, the OpenJS Foundation has a sale running on Node.js Certifications and Trainings with savings up to 75%. There is also a new testing environment built for the Node.js Certifications. :

https://openjsf.org/certification/

**Comment by bnb** [comment]
Further edit for structure and punctuation. Specifically, I'm editing the testing environment so it's not conceptually detached for those who aren't familiar with it already. Also trying to minimize sales lingo since that doesn't particularly fit in to the Node.js voice that's been used so far.

> The OpenJS Foundation has a sale running on Node.js Certifications and Trainings and is offering up to 75% through April 9th, alongside the release of their new testing environment built for the Node.js Certifications:
>
>https://openjsf.org/blog/2021/03/29/node-js-certifications-and-training-sale/

**Comment by joesepi** [comment]
I posted this to both LinkedIn and Facebook.

**Comment by bnb** [comment]
since these are posted, I'll close this.
